#cache:
#  directories:
#    - node_modules

install:
  - npm install 
  - pushd node_modules/qxcompiler 
  - npm link
  - popd

script:
  - qx compile --target=build
  - ./generate.py api
  - mv api build-compiled/

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  local-dir: build-compiled
  on:
    branch: master