language: node_js
node_js: "10"

dist: trusty

#cache:
#  directories:
#    - node_modules

script:
  - qx compile --target=build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: compiled/build
  on:
    branch: master
